### ISSUE TITLE
User sees buttons change to "loading" state immediately after clicking

### ISSUE THREAD

**Issue by melissasamworth** [Yellow987/CageFreeHub#106]
Design: https://www.figma.com/proto/JKLMt4PUolkBSBrp89PKKL/Cage-Free-Hub%3A-Mockups?page-id=3859%3A17305&node-id=3925%3A7959&viewport=-1294%2C309%2C0.5&scaling=min-zoom&starting-point-node-id=3925%3A7959
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
Acceptance criteria:
For all buttons on platform: 

If load takes more than 2 seconds, change the button to a loading state

p1
- Loading dots (animated SVG) replaces the text

p2 (optional, if it's really easy)
- button background goes to 50%
- the pointing hand cursor no longer appears on hover

I don't know how animated SVGs work from a technical perspective, but the fourth from left here (or something like it) would be great: https://codepen.io/nikhil8krishnan/pen/rVoXJa
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
Priority:
medium (do after all high items are done)
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
Created time:
2023-02-21T04:33:01.000Z
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
ID:
recEUQqMLsYb84fXI

**Comment by Yellow987** [comment]
sure I can add a loading symbol from design like this: https://mui.com/material-ui/react-progress/

**Comment by melissasamworth** [comment]
Yes exactly!

**Comment by Yellow987** [comment]
Hey Melissa, I don't see any problem with "User seeing buttons change to "loading" state immediately after clicking".

User story is that "I want user to know that when they cannot click a proceed button(ex. disabled) it is because something is uploading/loading."

Maybe im not understanding the ask though. May you provide examples of what you see vs what you expect?

**Comment by Yellow987** [comment]
closing issue as was about website being slow(its not anymore)
