### ISSUE TITLE
Add hotjar tracking code to the head of every page

### ISSUE THREAD

**Issue by melissasamworth** [Yellow987/CageFreeHub#108]
Design: 
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
Acceptance criteria:
Purpose: I want to try using Hotjar so we can see how users are interacting with the product, and gain insights for potential design changes! 

Insert the following code into the head tag of every page

<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3388268,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
Priority:

––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
Created time:
2023-03-01T02:50:44.000Z
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
ID:
recyCfemA2q7nqNLy

**Comment by Yellow987** [comment]
Hey Melissa, I added hotjar to preprod & it confirms it is installed, with corresponding hotjar account(which you should have access to) 
https://insights.hotjar.com/sites/3393197/overview
https://freerangeeggfarm-26736.web.app

^I'm not sure how this works/tracks. Are you familiar? May you take the lead to investigate if this meets our criteria?

I am able to deploy hotjar to prod whenever your ready as well.

**Comment by melissasamworth** [comment]
Great! Yes I will look into this.
