### ISSUE TITLE
stuck on "Product details" and clicking next does nothing

### ISSUE THREAD

**Issue by melissasamworth** [Yellow987/CageFreeHub#90]
this error occured when I was rejected, clicked "finalize profile", and then went through the setup wizard process again (I think it only happens in this case). But I am stuck on "Product details" and clicking next does nothing

https://airtable.com/app9UmusDgFydz5Bu/tblKFJNssWgzYEoFv/viwcSlYdz6taHnXgG/recFf5o1NrNJ3WbaR?blocks=hide

**Comment by Yellow987** [comment]
I think you meant production details, fixed!
